version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run: echo "REACT_APP_SENTRY_DSN=${SENTRY_DSN}" >> .env
      - run: echo "REACT_APP_VERSION=$npm_package_version" >> .env
      - run: yarn deploy
